services:
  my-toolkit:
    image: ghcr.io/mfathi91/my-toolkit:latest
    pull_policy: always
    container_name: my-toolkit
    ports:
      - "8765:8765"
    volumes:
      - ./temp:/app/temp
      - ./output:/app/output
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
